### ISSUE TITLE
Npm error while when packing bcrypt as an external modules

### ISSUE THREAD

**Issue by sudsbangs** [serverless-heaven/serverless-webpack#1063]
# This is a (Bug Report / Feature Proposal)

## Description
I am using "serverless-webpack": "^5.6.1", which uses bcrypt npm package. I have no issues in building the native modules using my docker which uses an alpine image mentioned here https://github.com/kelektiv/node.bcrypt.js/wiki/Installation-Instructions#rhel-and-centos. However when theserverless-webpack starts packing external modules it comes back with error Error: npm install failed with code 1 at ChildProcess.<anonymous> (/usr/src/app/node_modules/serverless-webpack/lib/utils.js:91:16) at ChildProcess.emit (events.js:400:28) at ChildProcess.emit (domain.js:475:12) at maybeClose (internal/child_process.js:1058:16) at Socket.<anonymous> (internal/child_process.js:443:11) at Socket.emit (events.js:400:28) at Socket.emit (domain.js:475:12) at Pipe.<anonymous> (net.js:686:12)

For bug reports:
* What went wrong? 
Error: npm install failed with code 1 
* What did you expect should have happened?
should have successfully bundled the webpack with externals bcrypt
* What was the config you used?
externals: {
    bcrypt: 'bcrypt',
}
* What stacktrace or error message from your provider did you see?
Error: npm install failed with code 1 at ChildProcess.<anonymous> (/usr/src/app/node_modules/serverless-webpack/lib/utils.js:91:16) at ChildProcess.emit (events.js:400:28) at ChildProcess.emit (domain.js:475:12) at maybeClose (internal/child_process.js:1058:16) at Socket.<anonymous> (internal/child_process.js:443:11) at Socket.emit (events.js:400:28) at Socket.emit (domain.js:475:12) at Pipe.<anonymous> (net.js:686:12)
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
  when using bcrypt the `serverless-webpack` fails to bundle 
* If there is additional config how would it look

Similar or dependent issue(s):
* #12345

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.6.1
* ***Webpack version you're using***: 5.59.1
* ***Serverless Framework Version you're using***: 3.1.1
* ***Operating System***: Docker Node:14-alpine
* ***Stack Trace (if available)***:
*Packing external modules: lodash@^4.17.21, bcrypt@^5.0.1, typeorm@^0.2.41, reflect-metadata@^0.1.13, typeorm-naming-strategies@^2.0.0, mysql2@^2.3.3

× Stack dev-cloud failed to deploy (38s)
Environment: linux, node 14.19.0, framework 3.1.1 (local), plugin 6.0.0, SDK 4.3.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: npm install failed with code 1
    at ChildProcess.<anonymous> (/usr/src/app/node_modules/serverless-webpack/lib/utils.js:91:16)
    at ChildProcess.emit (events.js:400:28)
    at ChildProcess.emit (domain.js:475:12)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)

**Comment by sudsbangs** [comment]
> `npm install failed with code 1` means the installation has failed, the current implementation swallowed stderr from the npm process but you may manually run them in an alpine shell `docker run -it --rm alpine` to see what is the actual error.
> 
> From my experience it could be caused by `bcrypt` not having a pre-built binary for alpine, and docker alpine does not comes with build tools. Another possibility is that alpine does not come with the necessary crypto libraries.
> 
> Either way you should install them before running `serverless-webpack`, hence the subsequent `npm install` spwan by it.

Thanks @vicary for answering. Yeah i did some pre-build for bcrypt using alphine docker image. I will try and give it a go as per your suggestion.
