### ISSUE TITLE
serverless-webpack with Codeship CI

### ISSUE THREAD

**Issue by radelcom** [serverless-heaven/serverless-webpack#235]
# This is a not a bug

## Description

has anyone here tried serverless-webpack with [Codeship](https://codeship.com/)? We were able to get everything setup properly in our local machines but once we integrate our CI Codeship to do the deployments, it craps out with this error. The only way we were able to get it to work is to get some of the dev dependencies to prod in our package.json which I think is not right.

Any help if greatly appreciated. tx in advance!

 ```
Serverless Error ---------------------------------------

  Serverless plugin "serverless-webpack" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.10.3
     Serverless Version:     1.23.0

```

this is how our `package.json` looks like now just to get it to build.
```
"devDependencies": {
    "babel-register": "^6.26.0",
    "chai": "^4.1.2",
    "codeclimate-test-reporter": "^0.4.1",
    "eslint": "^4.6.1",
    "lambda-tester": "^2.8.1",
    "mocha": "^3.5.3",
    "nyc": "^11.2.1",
    "rewire": "^2.5.2",
    "sinon": "^3.2.1"
  },
  "dependencies": {
    "aws-sdk": "^2.114.0",
    "babel-core": "^6.25.0",
    "babel-eslint": "^8.0.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-source-map-support": "^1.0.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-3": "^6.24.1",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.23.0",
    "eslint-loader": "^1.9.0",
    "moment": "^2.18.1",
    "node-fetch": "^1.7.3",
    "serverless-webpack": "^3.0.0",
    "source-map-support": "^0.4.14",
    "webpack": "^3.0.0",
    "webpack-node-externals": "^1.6.0",
    "winston": "^2.3.1"
  }
```

**Comment by HyperBrain** [comment]
Can you try to set `SLS_DEBUG=*` to make Serverless show the error more descriptive and add the stacktrace? It might be something that the configuration is different locally and with Codeship - the stacktrace could shed some light onto that.

**Comment by radelcom** [comment]
@HyperBrain 

again, thank you for the speedy response! here is the logs when I add `SLS_DEBUG=*`

```
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function

  Error --------------------------------------------------

  Cannot find module 'serverless-webpack'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: Cannot find module 'serverless-webpack'
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at plugins.forEach.error (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:89:24)
at Array.forEach (native)
at PluginManager.loadPlugins (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:87:13)
at PluginManager.loadServicePlugins (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:133:10)
at PluginManager.loadAllPlugins (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:83:10)
at service.load.then (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/Serverless.js:64:28)
From previous event:
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
at __dirname (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/bin/serverless:25:46)
at Object.<anonymous> (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/bin/serverless:43:4)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:390:7)
at startup (bootstrap_node.js:150:9)
at bootstrap_node.js:505:3

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.10.3
     Serverless Version:     1.23.0
```

**Comment by HyperBrain** [comment]
The callstack shows explicitly that the plugin indeed could not be found:
`at plugins.forEach.error (/home/rof/.nvm/versions/node/v6.10.3/lib/node_modules/serverless/lib/classes/PluginManager.js:89:24)`
and that it's not a crash in the plugin.

Can you check if the `serverless-webpack` plugin is available and accessible on the build server?

**Comment by radelcom** [comment]
Sadly, I dont have access to it. see the build server spawns a VM and we have all the steps/script to prepare the environment like npm install, npm install -g serverless and etc.

looking at the npm install logs, it shows the serverless-webpack got installed
```
...
rewire@2.5.2 
serverless-webpack@3.1.0 
archiver@2.0.3 
...
```

**Comment by radelcom** [comment]
hmmm, i think I found our culprit. for some reason we do `npm prune --production` before `sls deploy` which basically remove the dev dependencies. 

question to more node expert here, what is the implication of not having the `npm prune -production` for deployments?

**Comment by HyperBrain** [comment]
You only need that if you use SLS without `serverless-webpack` because the packaging for SLS was buggy for a long time and included dev dependencies. As far as I know there are even now still problems with certain setups.

With `serverless-webpack` the project modules are irrelevant and the plugin will install the needed modules on its own separately, so that it is guaranteed that only the needed modules are packaged.
So you do not need to prune any production dependencies in this case.
