### ISSUE TITLE
webpack is not defined 

### ISSUE THREAD

**Issue by kencckw** [serverless-heaven/serverless-webpack#267]
The project is fine on OSX.

```
C:\Users\Ken\projects\__MASK__>set SLS_DEBUG=*
C:\Users\Ken\projects\__MASK__>sls deploy
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command webpack
Serverless: Load command webpack:invoke
Serverless: Load command webpack:watch
Serverless: Load command webpack:serve
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook before:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: WARNING: Plugin ServerlessWebpack uses deprecated hook after:deploy:createDeploymentArtifacts,
                     use package:createDeploymentArtifacts hook instead
Serverless: Load command create
Serverless: Load command create:test
Serverless: Load command create:function
Serverless: Load command invoke
Serverless: Load command invoke:test
Serverless: Load command offline
Serverless: Load command offline:start
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Could not load webpack config 'C:\Users\Ken\projects\__MASK__\webpack.config.js'

  Reference Error ----------------------------------------

  webpack is not defined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

ReferenceError: webpack is not defined
    at Object.<anonymous> (C:\Users\Ken\projects\__MASK__\webpack.config.js:27:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at ServerlessWebpack.validate (C:\Users\Ken\projects\__MASK__\node_modules\serverless-webpack\lib\validate.js:103:30)
From previous event:
    at PluginManager.invoke (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:360:22)
    at PluginManager.spawn (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:378:17)
    at Deploy.BbPromise.bind.then.then (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\plugins\deploy\deploy.js:107:10)
    at BbPromise.reduce (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:360:22)
    at PluginManager.run (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:391:17)
    at variables.populateService.then (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:86:74)
    at serverless.init.then (C:\Users\Ken\AppData\Roaming\npm\node_modules\serverless\bin\serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           6.10.3
     Serverless Version:     1.23.0

C:\Users\Ken\projects\__MASK__>dir
....
2017/11/04               759 webpack.config.js
....
```

package.json
```
{
    "devDependencies": {
        "@types/aws-lambda": "0.0.18",
        "@types/jest": "^21.1.5",
        "@types/node": "^8.0.47",
        "jest": "^21.2.1",
        "js-yaml": "^3.10.0",
        "lambda-wrapper": "^0.2.1",
        "serverless-jest-plugin": "^0.1.6",
        "serverless-offline": "^3.16.0",
        "serverless-webpack": "^3.1.2",
        "ts-jest": "^21.1.4",
        "ts-loader": "^2.3.7",
        "tslint": "^5.8.0",
        "tslint-react": "^3.2.0",
        "tslint-react-recommended": "^1.0.15",
        "typescript": "^2.5.2",
        "webpack": "^3.8.1"
    },
    "dependencies": {
        "lodash": "^4.17.4"
    }
}
```

**Comment by kencckw** [comment]
Problem in webpack.DefinePlugin.

    plugins: [
        // new webpack.DefinePlugin({}),
    ]

**Comment by HyperBrain** [comment]
@kencckw . Yes, it seems you did not do `const webpack=require('webpack');` in your webpack config.
