### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed (when invoke local)

### ISSUE THREAD

**Issue by richburdon** [serverless-heaven/serverless-webpack#284]
# This is a Bug Report

## Description

I'm using babel and webpack (normal configuration; works outside of serverless).

In the webpack entry I have `babel-polyfill` declared before my entry point. This works when deployed. However, when invoked locally via `sls invoke local -f test` I get the error below:

~~~~
Error: only one instance of babel-polyfill is allowed
~~~~

If I remove the `babel-polyfill` then it works locally, but then fails when deployed (as expected), with:

~~~~
regeneratorRuntime is not defined
~~~~

`.babelrc`
~~~~
{
  "presets": [
    ["env", {
      "debug": true,
      "targets": {
        "node": "6.10"
      },
      "useBuiltIns": true
    }],

    "stage-0"
  ]
}
~~~~

`webpack.conf.js`
~~~~
const path = require('path');

module.exports = {
  target: 'node',

  entry: {
    handler: [
      'babel-polyfill', path.resolve('./handler.js')
    ]
  },

  output: {
    path: path.resolve('./dist'),
    filename: '[name].js',
    libraryTarget: 'commonjs'
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,    // Don't transpile deps.
        include: [
          path.resolve('.')
        ],
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: './dist/babel-cache/'
          }
        }
      }
    ]
  }
};
~~~~

`serverless.yml`
~~~~
service: testing

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: dev

plugins:
  - "serverless-offline"
  - "serverless-webpack"

functions:
  test:
    handler: handler.test
    description: "Test service."
    events:
      - http:
          path: test
          method: get
          cors: true
~~~~

## Related

https://github.com/dherault/serverless-offline/issues/325

## Additional Data

* ***Serverless-Webpack Version you're using***: 4.0.0
* ***Webpack version you're using***: 3.8.1
* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: OS/X
* ***Stack Trace (if available)***: 

~~~~
sls invoke local -f test
Serverless: Bundling with Webpack...
babel-preset-env: `DEBUG` option

Using targets:
{
  "node": "6.10"
}

Modules transform: commonjs

Using plugins:
  transform-exponentiation-operator {"node":"6.10"}
  transform-async-to-generator {"node":"6.10"}
  syntax-trailing-function-commas {"node":"6.10"}

Using polyfills:
  es7.object.values {"node":"6.10"}
  es7.object.entries {"node":"6.10"}
  es7.object.get-own-property-descriptors {"node":"6.10"}
  es7.string.pad-start {"node":"6.10"}
  es7.string.pad-end {"node":"6.10"}

Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/Users/burdon/projects/src/xxx/darkstar/sub/testing/dist/service/handler.js:3694:9)
    at __webpack_require__ (/Users/burdon/projects/src/xxx/darkstar/sub/testing/dist/service/handler.js:20:30)
    at Object.<anonymous> (/Users/burdon/projects/src/xxx/darkstar/sub/testing/dist/service/handler.js:3676:1)
    at __webpack_require__ (/Users/burdon/projects/src/xxx/darkstar/sub/testing/dist/service/handler.js:20:30)
    at /Users/burdon/projects/src/xxx/darkstar/sub/testing/dist/service/handler.js:63:18
    at Object.<anonymous> (/Users/burdon/projects/src/xxx/darkstar/sub/testing/dist/service/handler.js:66:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/Users/burdon/.config/yarn/global/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:251:33)
    at AwsInvokeLocal.invokeLocal (/Users/burdon/.config/yarn/global/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:125:19)
    at AwsInvokeLocal.tryCatcher (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/burdon/.config/yarn/global/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
~~~~

**Comment by HyperBrain** [comment]
Hi @richburdon , thanks for raising the issue.

I found one issue in your `serverless.yml`:
```
plugins:
  - "serverless-offline"
  - "serverless-webpack"
```
**You have to switch the order of the two plugins**. Webpack must precede offline, because only that makes sure that the webpack plugin is used at the right position.
Can you change that and give feedback if the behavior changed (with invoke local and with offline)?

If it should not change, the behavior (the error message) is quite strange, because invoke local only calls the function exactly once and then exits. Only if you enable watch mode with `--watch`, it will be recompiled and executed again.

BTW: as soon as #266 is implemented, you should switch to use the automatic entry resolution with `slsw.lib.entries` so that you can benefit from individual packaging.

**Comment by richburdon** [comment]
Hi @HyperBrain, thanks for the quick update. 

It didn't make any difference, but it did prompt me to find the answer -- although I don't understand it yet:

This is a test project for a serverless plugin that I'm developing. The plugin also uses babel. I included `babel-polyfill` in the webpack entry for the plugin's bundle; it seems that that causes the double `babel-polyfill`?; i.e., I'm guessing that the plugin toolchain itself is complaining rather than the lambda function? If I remove `babel-polyfill` from either the function's bundle OR the plugin's bundle then things work. And this explains why it works in production?

So I'm guessing the plugin "contaminates" the function's Javascript runtime?

Does this make sense?

**Comment by HyperBrain** [comment]
Yes ... somehow 😄 . A Serverless plugin that loads `babel-polyfill` will have it injected in the Serverless process, i.e. it will affect all other plugins running in the build/deploy process - but not the compiled function code. It might be that webpack internally loads `babel-polyfill` too to make some decisions?

It really looks like a clash in the Serverless process according to your description. The cleanest solution would be to get rid of the explicit require in your plugin, so that it does not pollute the build environment enymore.

There's a lot of discussion about this problem (including babel-polyfill twice throws). In this comment, someone suggests to use `babel-runtime` (https://github.com/babel/babel/issues/4019#issuecomment-314858278). Can you try that in your plugin as that is the only thing you explicitly have under control (the users utilizing it can do anything).

**Comment by HyperBrain** [comment]
@richburdon Did you have any success with the issue?

**Comment by HyperBrain** [comment]
@richburdon Any news here? Could you please give feedback on the issue or can I close it?

**Comment by drjuarez** [comment]
@HyperBrain I was running into a similar error and fixed it using the suggested babel-transform-runtime and invoking the option in the cli on my server build.

**Comment by HyperBrain** [comment]
@drjuarez Thanks for the feedback.

I'll close this issue now. Feel free to continue the discussion if needed.
