### ISSUE TITLE
Module .path not found for WebPack

### ISSUE THREAD

**Issue by QAnders** [serverless-heaven/serverless-webpack#296]
(From https://github.com/serverless/serverless/issues/4538)

Running sls invoke for a project using WebPack throws a "Module not found" exception.
```
Serverless: Bundling with Webpack...
Time: 682ms
         Asset     Size  Chunks             Chunk Names
    handler.js   8.3 kB       0  [emitted]  handler
handler.js.map  2.46 kB       0  [emitted]  handler
   [0] ./handler.js 5.73 kB {0} [built] [failed] [1 error]

ERROR in ./handler.js
Module build failed: Error: Cannot find module './path'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-traverse/lib/index.js:10:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-template/lib/index.js:69:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-helpers/lib/helpers.js:5:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-helpers/lib/index.js:12:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-core/lib/transformation/file/index.js:30:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-core/lib/api/node.js:6:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-core/index.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/babel-loader/lib/index.js:3:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadLoader (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/Compilation.js:151:10)
    at moduleFactory.create (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/Compilation.js:456:10)
    at factory (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
    at /mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:69:10)
    at process.nextTick (/mnt/d/Q/GitHub-Repos/qip-lambda-invoice-routing/node_modules/webpack/lib/NormalModuleFactory.js:194:7)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  Error --------------------------------------------------

  Webpack compilation error, see above

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.9.1
     Serverless Version:     1.24.1
```

Function from handler.js:
```
export const createeInvoiceHandler = async (event, context, cb) => {
  const functionName = 'createeInvoice';
  logHelper({ event, context }, [functionName]);

  try {
    const result = await createeInvoice(event, context.clientContext);
    return cb(null, {
      statusCode: 200,
      data: result
    });
  } catch (err) {
    errorReporter(err, functionName, { event, context });
    return cb(err, null);
  }
};
```

Command:
`sls invoke local --function createeInvoice --path ../test.createeinvoice.json  --contextPath /mnt/d/Q/GitHub-Repos/test.createeinvoice.context.json`

Serverless.yml:
```
service: qip-lambda-invoice-routing

plugins:
  - serverless-webpack
  - serverless-secrets-plugin

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  memorySize: 512
  timeout: 15

custom:
  webpackIncludeModules: true
```

**Comment by HyperBrain** [comment]
@QAnders Thanks for moving the issue. The `handler.js` looks good.
Can you provide the `webpack.config.js` and the `function: createeInvoice` from the `serverless.yml` too?
It might be that the declaration of the function handler together with the webpack config leads to the issue (I use invoke local at work frequently and did not encounter any issues yet).

**Comment by QAnders** [comment]
I have too been using sls invoke local and it has worked fine until I upgraded Node.js to v8.9.1...

```
const slsw = require('serverless-webpack');
const path = require('path');
var nodeExternals = require('webpack-node-externals');

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  devtool: 'source-map',
  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: ['babel-loader'],
        include: __dirname,
        exclude: /node_modules/
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  },
  externals: [nodeExternals()],
  node: {
    fs: 'empty'
  }
};
```

```
export const createeInvoiceHandler = async (event, context, cb) => {
  const functionName = 'createeInvoice';
  logHelper({ event, context }, [functionName]);

  try {
    const result = await createeInvoice(event, context.clientContext);
    return cb(null, {
      statusCode: 200,
      data: result
    });
  } catch (err) {
    errorReporter(err, functionName, { event, context });
    return cb(err, null);
  }
};
```

**Comment by QAnders** [comment]
I can actually see that `./path` is missing fromt eh directory of `/node_modules/babel-traverse/lib/index.js`

**Comment by QAnders** [comment]
I ran a `npm install babel-traverse --save` and now it seems to be back and working...

**Comment by HyperBrain** [comment]
Strange. Apparently npm has some issues. Another issue in the repo from today was also a npm issue were the npm cache got corrupted. Good to hear that it now works for you 👍

**Comment by QAnders** [comment]
Yaeh, seems to be som nvm/npm based thing... Closing!

Massive thanks (again) for your quick response!
