### ISSUE TITLE
Webpack 4 example: Cannot find module 'source-map-support/register'

### ISSUE THREAD

**Issue by mataide** [serverless-heaven/serverless-webpack#357]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
The example with the babel and webpack4 doesnt work. It dont find the module 'source-map-support/register'
* What stacktrace or error message from your provider did you see?
```
{
    "errorMessage": "Cannot find module 'source-map-support/register'",
    "errorType": "Error",
    "stackTrace": [
        "Function.Module._load (module.js:417:25)",
        "Module.require (module.js:497:17)",
        "require (internal/module.js:20:19)",
        "Object.module.exports.module.exports.body.game (/var/task/api/firestore/room/handler.js:83:18)",
        "__webpack_require__ (/var/task/api/firestore/room/handler.js:24:30)",
        "Object.<anonymous> (/var/task/api/firestore/room/handler.js:283:1)",
        "__webpack_require__ (/var/task/api/firestore/room/handler.js:24:30)",
        "/var/task/api/firestore/room/handler.js:76:18",
        "Object.<anonymous> (/var/task/api/firestore/room/handler.js:79:10)"
    ]
}
--------------------------------------------------------------------
START RequestId: 71ed6d73-322e-11e8-823c-67f345401cfd Version: $LATEST
Unable to import module 'api/firestore/room/handler': Error
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.module.exports.body.game (/var/task/api/firestore/room/handler.js:83:18)
    at __webpack_require__ (/var/task/api/firestore/room/handler.js:24:30)
    at Object.<anonymous> (/var/task/api/firestore/room/handler.js:283:1)
    at __webpack_require__ (/var/task/api/firestore/room/handler.js:24:30)
    at /var/task/api/firestore/room/handler.js:76:18
    at Object.<anonymous> (/var/task/api/firestore/room/handler.js:79:10)
END RequestId: 71ed6d73-322e-11e8-823c-67f345401cfd
REPORT RequestId: 71ed6d73-322e-11e8-823c-67f345401cfd  Duration: 22.75 ms      Billed Duration: 100 ms         Memory Size: 256 MB     Max Memory Used: 20 MB
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look
```
{
  "name": "proak-realtime",
  "version": "0.1.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build-funcs": "babel api/firestore --out-dir dist/firestore"
  },
  "author": "serverless.com",
  "license": "MIT",
  "dependencies": {
    "firebase-admin": "^5.11.0",
    "source-map-support": "^0.5.4"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-source-map-support": "^2.0.1",
    "babel-preset-env": "^1.6.1",
    "serverless-offline": "^3.18.0",
    "serverless-webpack": "^5.1.1",
    "webpack": "^4.3.0",
    "webpack-node-externals": "^1.6.0"
  }
}

```
* ***Serverless Framework Version you're using***: 1.26.1

**Comment by HyperBrain** [comment]
Oh, indeed. Thanks for the info. I'll try to fix it as it does not seem to package the source-map-support module correctly.

**Comment by HyperBrain** [comment]
This is strange. I did a `npx sls package` to verify the package contents that are uploaded to AWS. It correctly contains the source-map-support module:
![image](https://user-images.githubusercontent.com/5524702/38024264-c2443a46-3284-11e8-9e20-26d1abeb345a.png)

Can you try to do a package too and check the contents of the zip file?

**Comment by mataide** [comment]
@HyperBrain, No, for me it dont have the source-map in the package. Just the handler.

webpack.config.js:

```
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
    entry: slsw.lib.entries,
    target: 'node',
    mode: slsw.lib.webpack.isLocal ? 'development': 'production',
    optimization: {
        // We no not want to minimize our code.
        minimize: false
    },
    performance: {
        // Turn off size warnings for entry points
        hints: false
    },
    devtool: 'nosources-source-map',
    externals: [nodeExternals()],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader'
                    }
                ],
            }
        ]
    },
    output: {
        libraryTarget: 'commonjs2',
        path: path.join(__dirname, '.webpack'),
        filename: '[name].js',
        sourceMapFilename: '[file].map'
    }
};
```

**Comment by HyperBrain** [comment]
Did you set `custom: webpack: includeModules: true` in your serverless.yml?

**Comment by mataide** [comment]
@HyperBrain I set it now. it bundle all the node_modules, the package now have >40mb and takes up to 10 min to deploy. is that correct? (Sorry, first time using your plugin)

**Comment by HyperBrain** [comment]
I assume that the `firebase-admin` module is the big one. If you inspect the build output it is referenced as external module.
Do you really need that module in your function?
If yes, you could try to bundle the firebase-admin into the code, so that only used parts are bundled with: `externals: [nodeExternals( { whitelist: [ "firebase-admin" ] } )]`

**Comment by HyperBrain** [comment]
BTW: There was a firebase related issue already opened in the past: https://github.com/serverless-heaven/serverless-webpack/issues/309
I don't know if any information from the comments there might help too. But in case you normally use Yarn instead of NPM, you should also set `custom: webpack: packager: yarn` which is much faster than npm.

**Comment by mataide** [comment]
I added: `externals: [nodeExternals( { whitelist: [ "firebase-admin" ] } )]`
And the package goes 46.55mb to 46.41mb.

And I am getting a Connection Time out:

```
λ serverless deploy function -f firestoreRoom
Serverless: Bundling with Webpack...
Time: 12887ms
Built at: 2018-3-28 12:14:37
                            Asset      Size  Chunks                    Chunk Names
    api/firestore/room/handler.js   278 KiB       0  [emitted]  [big]  api/firestore/room/handler
api/firestore/room/handler.js.map  40.8 KiB       0  [emitted]         api/firestore/room/handler
Entrypoint api/firestore/room/handler [big] = api/firestore/room/handler.js api/firestore/room/handler.js.map
   [2] ./node_modules/firebase-admin/lib/utils/deep-copy.js 2.6 KiB {0} [built]
   [7] external "source-map-support/register" 42 bytes {0} [built]
   [9] external "@google-cloud/firestore" 42 bytes {0} [built]
  [10] external "@firebase/database" 42 bytes {0} [built]
  [11] ./node_modules/firebase-admin/lib/storage/storage.js 4.93 KiB {0} [built]
  [12] ./node_modules/firebase-admin/lib/messaging/messaging.js 46.3 KiB {0} [built]
  [13] ./node_modules/firebase-admin/lib/auth/auth.js 14.8 KiB {0} [built]
  [16] external "json.date-extensions" 42 bytes {0} [built]
  [33] ./node_modules/firebase-admin/lib/firebase-namespace.js 17.6 KiB {0} [built]
  [34] ./node_modules/firebase-admin/lib/default-namespace.js 1.16 KiB {0} [built]
  [35] ./node_modules/firebase-admin/lib/index.js 712 bytes {0} [built]
  [36] ./api/vendor/google/dev/proak-firestore.json 2.28 KiB {0} [built]
  [37] ./api/lib/response.js 4.51 KiB {0} [built]
  [38] ./api/firestore/room/post/action.js 937 bytes {0} [built]
  [39] ./api/firestore/room/handler.js 771 bytes {0} [built]
    + 25 hidden modules
Serverless: Package lock found - Using locked versions
Serverless: Packing external modules: source-map-support@^0.5.4, @google-cloud/firestore@0.13.0, @firebase/database@0.2.1, jsonwebtoken@8.1.0, json.date-extensions@^1.2.2, @google-cloud/storage@1.6.0, node-forge@0.7.1
Serverless: Packaging function: firestoreRoom...
Serverless: Uploading function: firestoreRoom (46.41 MB)...

  Serverless Error ---------------------------------------

  Connection timed out after 120000ms


```

**Comment by HyperBrain** [comment]
@gastonmorixe, @alopes, @shwanton, @samwiseduzer you all commented in #309 . Does anyone of you have a clue how to manage and include firebase, without including the whole package (which is HUGE)?

**Comment by mataide** [comment]
@HyperBrain I have manage to include only the feature that I needed (Firestore) than the package is a little smaller and it dont hit the Timed out but still take 15-20min to upload.

But for the whole firebase-admin, even if I set a higher timed out, it dont upload, gives me an error of signature expiration.
