### ISSUE TITLE
Bug Report. Node.js 8.10. Building for Production. serverless-webpack 5.1.1.

### ISSUE THREAD

**Issue by OlzhasAlexandrov** [serverless-heaven/serverless-webpack#363]
# Bug Report

## Description

- What went wrong?
  - Migration from 6.10 to 8.10

- What was the config you used?
  - Changed `targets` in .babelrc from `6.10` to `8.10`
  - Changed runtime in serverless.yml from 6.10 to `runtime: nodejs8.10`

- What stacktrace or error message from your provider did you see?
  - It doesn't give any meaningful error, I even removed uglify from the webpack config, but still receive without produced file:
```sh
ERROR in Unexpected token (1106:32)
```

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.1.1
* ***Webpack version you're using***: 4.4.1
* ***Serverless Framework Version you're using***: 1.26.1
* ***Operating System***: MacOS High Sierra 10.13.3
* ***Stack Trace (if available)***:
```sh
Arguments: 
  /usr/local/Cellar/node/9.10.1/bin/node /usr/local/Cellar/yarn/1.5.1_1/libexec/bin/yarn.js _aws deploy

PATH: 
  /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/da404/projects/upwork/bitcoindepot/3-backend/graphql-serverless-programmatic/node_modules/.bin:/Users/da404/projects/cloud/google-cloud-sdk/bin:/Users/da404/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/da404/projects/cloud/google-cloud-sdk/bin:/Users/da404/.pyenv/shims:/usr/local/sbin:/usr/local/sbin

Yarn version: 
  1.5.1

Node version: 
  9.10.1

Platform: 
  darwin x64

npm manifest: 
  {
    "name": "graphql",
    "version": "0.1.0",
    "private": true,
    "repository": {
      "type": "git",
      "url": "git@github.com:BitcoinDepot/GraphQL.git"
    },
    "lint-staged": {
      "{aws,graphql}/**/*.{js,json,css}": [
        "npm run code:fix",
        "git add"
      ]
    },
    "//": [
      "===== COMMENTS FOR SCRIPTS =====",
      "_scriptName - !IGNORE! underscore is used to highlight a child script (used by another script)",
      "precommit - using husky, autoclean code styling before a git commit",
      "code:fix - fix linting errors in parallel using eslint & prettier",
      "analyze - this script accepts scriptName to run analysis by setting up Webpack Monitor",
      "start - start local development",
      "start:prod - start production bundle in local development",
      "deploy:all - deploy all lambda functions to aws",
      "deploy:functionName - deploy a particular lambda function to aws",
      "deploy:fake-db - deploy FAKE database to aws",
      "port-8000 - free port 8000, sometimes DynamoDB keeps using it"
    ],
    "config": {
      "LINT_PATH": "\"{aws,graphql}/**/*.{js}\"",
      "ENV_LOCAL": "env-cmd env/local.env",
      "ENV_PROD": "env-cmd env/.prod.env"
    },
    "scripts": {
      "precommit": "lint-staged",
      "_generate-fake-data": "cd aws/dynamoDB && babel-node faker.js",
      "_install:dynamoDB": "sls dynamodb install",
      "_mfa-auth": "eval \"`aws-auth-helper bitcoindepot`\"",
      "_aws": "$npm_package_config_ENV_PROD sls --stage=production",
      "code:fix": "eslint --fix $npm_package_config_LINT_PATH",
      "analyze": "ENV_ANALYZE=true yarn",
      "prestart": "$npm_package_config_ENV_LOCAL run-p _generate-fake-data _install:dynamoDB",
      "start": "$npm_package_config_ENV_LOCAL sls offline start --noAuth",
      "start:prod": "$npm_package_config_ENV_PROD sls offline start --noAuth",
      "faker": "graphql-faker --extend http://localhost:4000/graphql",
      "deploy:all": "yarn _aws deploy",
      "deploy:graphql": "yarn _aws deploy function -f graphql",
      "deploy:playground": "yarn _aws deploy function -f playground",
      "deploy:fake-db": "yarn _mfa-auth && yarn _generate-fake-data && env-cmd ../../env/.aws.env babel-node deploy-to-aws.js",
      "port-8000": "kill $(lsof -t -i:8000)",
      "logs": "$npm_package_config_ENV_PROD sls logs -f graphql --startTime 5m"
    },
    "dependencies": {
      "apollo-server-lambda": "1.3.4",
      "aws-lambda": "^0.1.2",
      "aws-xray-sdk": "^1.2.0",
      "graphql": "^0.13.2",
      "graphql-date": "^1.0.3",
      "graphql-playground-middleware-lambda": "^1.5.0",
      "graphql-type-json": "^0.2.0",
      "jsonwebtoken": "^8.2.0",
      "node-fetch": "^2.1.2",
      "oauth": "^0.9.15",
      "uuid": "^3.2.1"
    },
    "devDependencies": {
      "aws-auth-helper": "^1.0.0",
      "aws-sdk": "^2.219.1",
      "babel-core": "^6.26.0",
      "babel-eslint": "^8.2.2",
      "babel-inline-import-loader": "^0.0.5",
      "babel-loader": "^7.1.4",
      "babel-minify-webpack-plugin": "^0.3.1",
      "babel-plugin-inline-import": "^2.0.6",
      "babel-plugin-inline-script-import": "^0.0.3",
      "babel-plugin-syntax-dynamic-import": "^6.18.0",
      "babel-plugin-syntax-object-rest-spread": "^6.13.0",
      "babel-plugin-transform-es2015-template-literals": "^6.22.0",
      "babel-plugin-transform-imports": "^1.5.0",
      "babel-plugin-transform-object-rest-spread": "^6.26.0",
      "babel-preset-env": "^1.6.1",
      "common-tags": "^1.7.2",
      "cors": "2.8.4",
      "env-cmd": "^7.0.0",
      "eslint": "^4.19.1",
      "eslint-config-prettier": "^2.9.0",
      "eslint-config-prettier-standard": "^1.0.1",
      "eslint-config-standard": "^11.0.0",
      "eslint-plugin-import": "^2.10.0",
      "eslint-plugin-node": "^6.0.1",
      "eslint-plugin-prettier": "^2.6.0",
      "eslint-plugin-promise": "^3.7.0",
      "eslint-plugin-standard": "^3.0.1",
      "faker": "^4.1.0",
      "husky": "^0.14.3",
      "imports-loader": "^0.8.0",
      "jsonfile": "^4.0.0",
      "lint-staged": "^7.0.3",
      "npm-run-all": "^4.1.2",
      "optimize-js-plugin": "^0.0.4",
      "prepack-webpack-plugin": "^1.1.0",
      "prettier": "^1.11.1",
      "serverless-dynamodb-client": "^0.0.2",
      "serverless-dynamodb-local": "^0.2.28",
      "serverless-offline": "^3.20.0",
      "serverless-plugin-tracing": "^2.0.0",
      "serverless-plugin-warmup": "^3.5.0-rc.1",
      "serverless-webpack": "^5.1.1",
      "strip-whitespace-loader": "^1.0.4",
      "uglifyjs-webpack-plugin": "^1.2.4",
      "webpack": "^4.4.1",
      "webpack-closure-compiler": "^2.1.6",
      "webpack-monitor": "^1.0.14",
      "webpack-node-externals": "^1.7.2"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: Command failed.
  Exit code: 1
  Command: sh
  Arguments: -c $npm_package_config_ENV_PROD sls --stage=production deploy
  Directory: /Users/da404/projects/upwork/bitcoindepot/3-backend/graphql-serverless-programmatic
  Output:
  
      at ProcessTermError.MessageError (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:186:110)
      at new ProcessTermError (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:226:113)
      at ChildProcess.<anonymous> (/usr/local/Cellar/yarn/1.5.1_1/libexec/lib/cli.js:30281:17)
      at ChildProcess.emit (events.js:180:13)
      at maybeClose (internal/child_process.js:936:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```

.babelrc:
```sh
{
  "presets": [
    ["env", {
      "targets": {
        "node": "8.10"
      }
    }]
  ],
  "plugins": [
    "syntax-dynamic-import", // tried with and without
    "transform-es2015-template-literals", // tried with and without
    "transform-object-rest-spread", // tried with and without
    "syntax-object-rest-spread", // tried with and without
    ["transform-imports", {
      "my-library": {
        "transform": "../../path/to/transform.js",
        "preventFullImport": true
      }
    }],
    ["babel-plugin-inline-import", {
      "extensions": [".gql"]
    }]
  ]
}
```

**Comment by OlzhasAlexandrov** [comment]
Also tried node versions: 
8.9.4 - 8.6.0 - 8.2.1 - 7.10.1 - 7.5.0
From http://node.green/
Building for all of these also produces the same error as above.

**Comment by HyperBrain** [comment]
You need to use the `babel-preset-stage2` preset together with the env preset when using `8.10` as target.

The problem is, that the pure env 8.10 preset does not include the spread rest operator and import.
So use 
```
"presets": [
    ["env", {
      "targets": {
        "node": "8.10"
      }
    }],
    "stage2"
  ],
```

We did the transistion yesterday for our projects and that way it works.

**Comment by OlzhasAlexandrov** [comment]
@HyperBrain Life saver! Just checked it and it worked! Thank You!
Allow me to improve your kindly provided solution, others, **be aware** that it's `stage-2` (DASH), not `stage2`.
So run install:
```sh
npm i -D babel-preset-stage-2
```
And then add:
```
  "presets": [
    ["env", {
      "targets": {
        "node": "8.10"
      }
    }],
    "stage-2"  // <------ dash here as well
  ],
```

**Comment by HyperBrain** [comment]
@OlzhasAlexandrov I updated my comment to include the dash (wrote the answer just too quickly 😄 ). Thanks for the correction.

**Comment by karlhorky** [comment]
`stage-2` includes a lot of things that most code won't need. For Object Rest/Spread Properties, since this is a stage 4 proposal (has been shipped in browsers) `babel-preset-env` starting with v2 (and also the v7+ `@babel/preset-env`) has [a `shippedProposals` option](https://github.com/babel/babel/issues/6970#issuecomment-349083308) that enables transpilation of stage 4 proposals.

So you can avoid installing the `stage-2` preset and just configure `preset-env`:

```json
"presets": [
  [
    "env",
    {
      "targets": {
        "node": "8.10"
      },
      "shippedProposals": true
    }
  ]
]
```

**Comment by karlhorky** [comment]
My full config for anyone interested, based on the Babel 7 beta packages:

```js
// .babelrc.js
module.exports = {
  comments: false,
  presets: [
    [
      // Use the `@babel/preset-env` package at version 7.0.0-beta.44
      '@babel/env',
      {
        targets: {
          node: '8.10',
        },
        shippedProposals: true,
        // Polyfill less
        useBuiltIns: 'usage',
      },
    ],
  ],
  plugins: [
    // For Flow types
    '@babel/transform-flow-strip-types',
    // For a better way of polyfilling of things that aren't transpiled
    [
      '@babel/transform-runtime',
      {
        polyfill: false,
        regenerator: false,
      },
    ],
  ],
};
```

Packages in `package.json` (note the beta `babel-loader` too):

```
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.44",
    "@babel/plugin-transform-flow-strip-types": "^7.0.0-beta.44",
    "@babel/plugin-transform-runtime": "^7.0.0-beta.44",
    "@babel/preset-env": "^7.0.0-beta.44",
    "babel-loader": "^8.0.0-beta.2",
```

**Comment by OlzhasAlexandrov** [comment]
I did, however, improve the original proposal of @HyperBrain a bit:
```json
{
  "presets": [ ["env", { "modules": false, "targets": { "node": "8.10" } }] ],
  "plugins": [
    // following 2 plugins were unnecessary from stage-2 (that includes stage-3 plugins)
    // "transform-class-properties",
    // "transform-async-generator-functions",
    "transform-object-rest-spread",
    "syntax-trailing-function-commas",
    "transform-async-to-generator",
    "transform-exponentiation-operator",
  ]
}
```

**Comment by karlhorky** [comment]
@OlzhasAlexandrov which version of `babel-preset-env` do you have? You need at least 2+. I did update the packages in the last few minutes again.

**Comment by OlzhasAlexandrov** [comment]
@karlhorky 
I was trying to use the exact same config and package versions as yours, it started to build with:
```js
module.exports = {
  comments: false,
  presets: [
    [
      "@babel/env",
      {
        targets: {
          node: "8.10",
        },
        shippedProposals: true,
        // Polyfill less
        useBuiltIns: "usage",
      },
    ],
  ],
  plugins: [
    // For Flow types
    // "@babel/plugin-syntax-object-rest-spread",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/transform-flow-strip-types",
    "@babel/transform-async-to-generator",
    "@babel/transform-exponentiation-operator",
    // For a better way of polyfilling of things that aren't transpiled
    [
      "@babel/transform-runtime",
      {
        polyfill: false,
        regenerator: false,
      },
    ],
  ],
}
```

**Comment by karlhorky** [comment]
Hm, not sure what the problem is, but those first two plugins shouldn't be required. The third one (exponentiation operator) however will be, since it's still Stage 3 as of now: https://github.com/rwaldron/exponentiation-operator/blob/966cc6ec7f2009e6a8e2d15de8baf60318cadd6b/readme.md

**Comment by shavo007** [comment]
@karlhorky  i have an issue #448 related to babel7 upgrade. Could you take a look please if you have time?

**Comment by lopezdp** [comment]
If anyone can help me out I am getting this error for this issue: 

```
RROR in ./getCaseRecord.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-preset-stage-3/lib/index.js
    at createDescriptor (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/partial.js:85:55)
    at Object.loadPartialConfig (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/@babel/core/lib/config/partial.js:110:18)
    at Object.<anonymous> (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:144:26)
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:3:103)
    at _next (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:5:194)
    at /Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:5:364
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:5:97)
    at Object._loader (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:224:18)
    at Object.loader (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:60:18)
    at Object.<anonymous> (/Users/MyDocs/DevOps/QuickAutoTags/services/v2.crm-case-record-api/node_modules/babel-loader/lib/index.js:55:12)
```

here is what is in my `.babelrc` file:

```
{
	"plugins": [],
	"presets": [
		["env", {"node": "10.14.1"}],
		"stage-3"
	]
}
```

Here are my dependencies in my `package.json`:

"devDependencies": {
    "aws-sdk": "^2.350.0",
    "babel-core": "^6.26.3",
    "babel-eslint": "^10.0.1",
    "babel-loader": "^8.0.6",
    "babel-plugin-source-map-support": "^2.0.1",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-3": "^6.24.1",
    "eslint": "^5.15.0",
    "eslint-config-standard": "^12.0.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-node": "^9.1.0",
    "eslint-plugin-promise": "^4.0.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-standard": "^4.0.0",
    "jest": "^24.8.0",
    "serverless-offline": "^5.0.0",
    "serverless-webpack": "^5.1.0",
    "webpack": "^4.16.2",
    "webpack-node-externals": "^1.6.0"
  },

**Comment by HyperBrain** [comment]
Did you already try to use babel v7 ?

```
  ...
    "@babel/core": "^7.3.4",
    "@babel/preset-env": "^7.3.4",
    "@babel/preset-stage3": "^7.0.0",
   ...
```
(The version numbers are examples only. Please check for the latest ones)

And please provide the Webpack and plugin versions you use.

**Comment by lopezdp** [comment]
@HyperBrain Thanks!

Im using WebPack4 and Yes in another build I have used Babel v7 successfully. I am upgrading my dependencies and moved up to 8 while using it with the serverless-webpack-plugin v5

I left you a copy of all of my dependencies with versions so you can see. I am assuming that serverless-webpack does not support babel v8 in this case eh?

What do you think?

**Comment by HyperBrain** [comment]
> serverless-webpack does not support babel v8 in this case eh?

Hmmm, might be possible. @serverless-heaven/serverless-webpack-team did anyone already test successfully with babel v8? If not this would make up a good addition for one of the next releases.

**Comment by lopezdp** [comment]
> > serverless-webpack does not support babel v8 in this case eh?
> 
> Hmmm, might be possible. @serverless-heaven/serverless-webpack-team did anyone already test successfully with babel v8? If not this would make up a good addition for one of the next releases.

Just in case it helps, the only way I could get it to work was to comment out `babel-loader` as such:

```
module: {
    rules: [
      {
        test: /\.js$/,
        // TODO: This was the fix to sls deploy
        // loader: "babel-loader",
        include: __dirname,
        exclude: /node_modules/
      }
    ]
  }
```
