### ISSUE TITLE
`nodeExternals` causes `Internal server error`

### ISSUE THREAD

**Issue by agreea** [serverless-heaven/serverless-webpack#367]
# This is a (Bug Report / Feature Proposal)
Bug Report

## Description

For bug reports:
* What went wrong?
Endpoints return `internal server error` from AWS when deploying with `nodeExternals`. 
Build doesn't show any errors when using `webpack@4.5.0`.
Build works locally.

* What did you expect should have happened?
Webpack should either throw an error during the build or the deployed lambda should be able to execute.

* What was the config you used?
```
const path = require('path')
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')

module.exports = {
  entry: slsw.lib.entries,
  stats: 'verbose',
  resolve: {
    mainFields: ['browser', 'main', 'module'],
    extensions: ['.js', '.json', '.ts']
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '/.webpack'),
    filename: '[name].js'
  },
  externals: [
    nodeExternals()
  ],
  target: 'node',
  module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'ts-loader'
          }
        ]
      },
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader'
      }
    ]
  }
}
```

* What stacktrace or error message from your provider did you see?
From CloudWatch:
```
Unable to import module 'handler': Error
at Function.Module._resolveFilename (module.js:469:15)
at Function.Module._load (module.js:417:25)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/handler.js:178:18)
at __webpack_require__ (/var/task/handler.js:20:30)
at Object.<anonymous> (/var/task/handler.js:151:25)
at __webpack_require__ (/var/task/handler.js:20:30)
at Object.defineProperty.value (/var/task/handler.js:132:15)
at __webpack_require__ (/var/task/handler.js:20:30)
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):

## Additional Data

* ***Serverless-Webpack Version you're using***:
`5.1.0`
* ***Webpack version you're using***:
4.5.0
* ***Serverless Framework Version you're using***:
1.26.1
* ***Operating System***: Mac OS Sierra
* ***Stack Trace (if available)***:
`webpack@4.5.0`:
```
Entrypoint handler = handler.js
chunk    {0} handler.js (handler) 17.8 KiB [entry] [rendered]
    > ./handler.ts handler
    [0] external "sequelize" 42 bytes {0} [depth 4] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require sequelize [1] ./models/db.ts 3:18-38
        cjs require sequelize [12] ./models/Item.ts 3:18-38
        cjs require sequelize [13] ./models/User.ts 3:18-38
        cjs require sequelize [14] ./models/Token.ts 3:18-38
        cjs require sequelize [15] ./models/Pin.ts 3:18-38
    [1] ./models/db.ts 476 bytes {0} [depth 3] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./db [2] ./models/index.ts 3:13-28
        cjs require ./db [12] ./models/Item.ts 4:13-28
        cjs require ./db [13] ./models/User.ts 4:13-28
        cjs require ./db [14] ./models/Token.ts 4:13-28
        cjs require ./db [15] ./models/Pin.ts 4:13-28
    [2] ./models/index.ts 429 bytes {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ../models [4] ./request-pin/index.ts 13:17-37
        cjs require ../models [4] ./request-pin/index.ts 14:17-37
        cjs require ../models [6] ./authenticate/index.ts 14:17-37
        cjs require ../models [8] ./auth/index.ts 14:17-37
        cjs require ../models [18] ./gql/resolvers.ts 14:17-37
    [3] external "ramda" 42 bytes {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ramda [4] ./request-pin/index.ts 12:10-26
        cjs require ramda [6] ./authenticate/index.ts 12:10-26
        cjs require ramda [8] ./auth/index.ts 12:10-26
        cjs require ramda [11] ./gql/orderString.ts 3:10-26
        cjs require ramda [18] ./gql/resolvers.ts 12:10-26
    [4] ./request-pin/index.ts 1.96 KiB {0} [depth 1] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./request-pin [22] ./handler.ts 11:22-46
    [5] external "uuid/v4" 42 bytes {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require uuid/v4 [6] ./authenticate/index.ts 13:15-33
    [6] ./authenticate/index.ts 2.21 KiB {0} [depth 1] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./authenticate [22] ./handler.ts 9:23-48
    [7] external "jsonwebtoken" 42 bytes {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require jsonwebtoken [8] ./auth/index.ts 13:12-35
    [8] ./auth/index.ts 3.29 KiB {0} [depth 1] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./auth [22] ./handler.ts 7:15-32
    [9] ./ping/index.ts 344 bytes {0} [depth 1] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./ping [22] ./handler.ts 5:15-32
   [10] ./gql/schema.gql 3.09 KiB {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./schema.gql [21] ./gql/index.ts 6:17-40
   [11] ./gql/orderString.ts 448 bytes {0} [depth 3] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./orderString [18] ./gql/resolvers.ts 15:22-46
   [12] ./models/Item.ts 325 bytes {0} [depth 3] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./Item [2] ./models/index.ts 10:15-32
   [13] ./models/User.ts 423 bytes {0} [depth 3] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./User [2] ./models/index.ts 8:15-32
   [14] ./models/Token.ts 356 bytes {0} [depth 3] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./Token [2] ./models/index.ts 6:16-34
   [15] ./models/Pin.ts 349 bytes {0} [depth 3] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./Pin [2] ./models/index.ts 4:14-30
   [16] ./secret/db.json 260 bytes {0} [depth 4] [built]
        [exports: dev, staging, production, default]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ../secret/db.json [1] ./models/db.ts 4:15-43
   [17] external "aws-sdk" 42 bytes {0} [depth 3] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require aws-sdk [18] ./gql/resolvers.ts 13:18-36
   [18] ./gql/resolvers.ts 2.48 KiB {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./resolvers [21] ./gql/index.ts 5:20-42
   [19] external "apollo-server-lambda" 42 bytes {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require apollo-server-lambda [21] ./gql/index.ts 4:15-46
   [20] external "graphql-tools" 42 bytes {0} [depth 2] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require graphql-tools [21] ./gql/index.ts 3:24-48
   [21] ./gql/index.ts 693 bytes {0} [depth 1] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        cjs require ./gql [22] ./handler.ts 3:14-30
   [22] ./handler.ts 457 bytes {0} [depth 0] [built]
        ModuleConcatenation bailout: Module is not an ECMAScript module
        single entry ./handler.ts  handler
```
`webpack@3.11.0`, Here's what you see when you try to build with `webpack@3.11.0` and `ts-loader@3.5.0`. Note the `[not cacheable]` tags on the external modules:
```
chunk    {0} handler.js (handler) 18.2 kB [entry] [rendered]
    > handler [4] ./handler.ts
    [0] external "ramda" 42 bytes {0} [depth 2] [not cacheable]
        cjs require ramda [8] ./gql/resolvers.ts 12:10-26
        cjs require ramda [15] ./gql/orderString.ts 3:10-26
        cjs require ramda [18] ./auth/index.ts 12:10-26
        cjs require ramda [20] ./authenticate/index.ts 12:10-26
        cjs require ramda [22] ./request-pin/index.ts 12:10-26
    [1] ./models/index.ts 429 bytes {0} [depth 2] [built]
        cjs require ../models [8] ./gql/resolvers.ts 14:17-37
        cjs require ../models [18] ./auth/index.ts 14:17-37
        cjs require ../models [20] ./authenticate/index.ts 14:17-37
        cjs require ../models [22] ./request-pin/index.ts 13:17-37
        cjs require ../models [22] ./request-pin/index.ts 14:17-37
    [2] ./models/db.ts 476 bytes {0} [depth 3] [built]
        cjs require ./db [1] ./models/index.ts 3:13-28
        cjs require ./db [11] ./models/Pin.ts 4:13-28
        cjs require ./db [12] ./models/Token.ts 4:13-28
        cjs require ./db [13] ./models/User.ts 4:13-28
        cjs require ./db [14] ./models/Item.ts 4:13-28
    [3] external "sequelize" 42 bytes {0} [depth 4] [not cacheable]
        cjs require sequelize [2] ./models/db.ts 3:18-38
        cjs require sequelize [11] ./models/Pin.ts 3:18-38
        cjs require sequelize [12] ./models/Token.ts 3:18-38
        cjs require sequelize [13] ./models/User.ts 3:18-38
        cjs require sequelize [14] ./models/Item.ts 3:18-38
    [4] ./handler.ts 457 bytes {0} [depth 0] [built]
    [5] ./gql/index.ts 693 bytes {0} [depth 1] [built]
        cjs require ./gql [4] ./handler.ts 3:14-30
    [6] external "graphql-tools" 42 bytes {0} [depth 2] [not cacheable]
        cjs require graphql-tools [5] ./gql/index.ts 3:24-48
    [7] external "apollo-server-lambda" 42 bytes {0} [depth 2] [not cacheable]
        cjs require apollo-server-lambda [5] ./gql/index.ts 4:15-46
    [8] ./gql/resolvers.ts 2.54 kB {0} [depth 2] [built]
        cjs require ./resolvers [5] ./gql/index.ts 5:20-42
    [9] external "aws-sdk" 42 bytes {0} [depth 3] [not cacheable]
        cjs require aws-sdk [8] ./gql/resolvers.ts 13:18-36
   [10] ./secret/db.json 259 bytes {0} [depth 4] [built]
        cjs require ../secret/db.json [2] ./models/db.ts 4:15-43
   [11] ./models/Pin.ts 349 bytes {0} [depth 3] [built]
        cjs require ./Pin [1] ./models/index.ts 4:14-30
   [12] ./models/Token.ts 356 bytes {0} [depth 3] [built]
        cjs require ./Token [1] ./models/index.ts 6:16-34
   [13] ./models/User.ts 423 bytes {0} [depth 3] [built]
        cjs require ./User [1] ./models/index.ts 8:15-32
   [14] ./models/Item.ts 325 bytes {0} [depth 3] [built]
        cjs require ./Item [1] ./models/index.ts 10:15-32
   [15] ./gql/orderString.ts 448 bytes {0} [depth 3] [built]
        cjs require ./orderString [8] ./gql/resolvers.ts 15:22-46
   [16] ./gql/schema.gql 3.16 kB {0} [depth 2] [built]
        cjs require ./schema.gql [5] ./gql/index.ts 6:17-40
   [17] ./ping/index.ts 344 bytes {0} [depth 1] [built]
        cjs require ./ping [4] ./handler.ts 5:15-32
   [18] ./auth/index.ts 3.37 kB {0} [depth 1] [built]
        cjs require ./auth [4] ./handler.ts 7:15-32
   [19] external "jsonwebtoken" 42 bytes {0} [depth 2] [not cacheable]
        cjs require jsonwebtoken [18] ./auth/index.ts 13:12-35
   [20] ./authenticate/index.ts 2.26 kB {0} [depth 1] [built]
        cjs require ./authenticate [4] ./handler.ts 9:23-48
   [21] external "uuid/v4" 42 bytes {0} [depth 2] [not cacheable]
        cjs require uuid/v4 [20] ./authenticate/index.ts 13:15-33
   [22] ./request-pin/index.ts 2.01 kB {0} [depth 1] [built]
        cjs require ./request-pin [4] ./handler.ts 11:22-46
```

**Comment by HyperBrain** [comment]
Hi @agreea . This error cannot be catched by the plugin, because it is something that one of your needed dependencies does not get packaged properly into the ZIP file. That might be due to dynamic requires that cannot be determined by webpack. Can you check if the packaging output of the plugins shows all node modules that are actually needed?
It would be helpful, if you also post your package.json and the output of `serverless package --verbose` where the external modules that are packaged are listed. Also check if you have set `custom: webpack: includeModules: true` in your serverless.yml file.

**Comment by HyperBrain** [comment]
BTW: You must not use the `package: include` setting with the plugin but you have to use the webpack copy file plugin to copy files into the compiled output. Otherwise the certs folder will be missing.

**Comment by agreea** [comment]
This was the fix!
```
# serverless.yml
custom:
  webpack:
    includeModules:
      forceInclude:
        - pg
```

Thank you 🙌
