### ISSUE TITLE
Trouble accessing external data file while integrating maxmind geoip library

### ISSUE THREAD

**Issue by janthonyeconomist** [serverless-heaven/serverless-webpack#371]
# This is a Bug Report

## Description
I get the following error when trying to integrate Maxmind's GeoIP library:
```
Error: ENOENT: no such file or directory, open '//data/GeoLite2-City.mmdb'
```
The top of my serverless.yml:
```
service:
  name: aws-nodejs-typescript
# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
```
I have the data file in `<project root>/data`
```
$ tree data
data
├── GeoLite2-ASN.mmdb
├── GeoLite2-City.mmdb
└── GeoLite2-Country.mmdb
```
And the handlers file is `<project root>/handler.ts`.  The code that is erroring out is:
```
const geoipDB = maxmind.openSync(__dirname + '/data/GeoLite2-City.mmdb');
```
I have even tried using the `geolite2` package, and loading it like `const geoipDB = maxmind.openSync(geolite2.paths.city);` thinking that perhaps if the file was in an NPM package it will be bundled correctly; however, it has the same problem.

The interesting part is, it works if I use `const geoipDB = maxmind.openSync('../../data/GeoLite2-City.mmdb');` because it happens to be relative to the build file `<project root>/.webpack/service/handler.js`; however, this seems dubious at best, and I'm not sure this will work once it goes live.

Am I missing some configuration that tells serverless to include this data file?  How can I access accurate paths seeing as the build moves the execution directory?

Similar or dependent issue(s):
* ?

## Additional Data

* ***Serverless-Webpack Version you're using***: ^3.0.0
* ***Webpack version you're using***: ^3.6.0
* ***Serverless Framework Version you're using***: 1.24.1
* ***Operating System***: macOS 10.13.3 (17D47)
* ***Stack Trace (if available)***:
```
{ Error: ENOENT: no such file or directory, open '//data/GeoLite2-City.mmdb'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Object.exports.openSync (/Users/judahanthony/workspace/testprep/gmat-api-serverless/.webpack/service/handler.js:63818:30)
    at Object.<anonymous> (/Users/judahanthony/workspace/testprep/gmat-api-serverless/.webpack/service/handler.js:25214:23)
    at Object.<anonymous> (/Users/judahanthony/workspace/testprep/gmat-api-serverless/.webpack/service/handler.js:25555:30)
    at __webpack_require__ (/Users/judahanthony/workspace/testprep/gmat-api-serverless/.webpack/service/handler.js:20:30)
    at /Users/judahanthony/workspace/testprep/gmat-api-serverless/.webpack/service/handler.js:63:18
    at Object.<anonymous> (/Users/judahanthony/workspace/testprep/gmat-api-serverless/.webpack/service/handler.js:66:10)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:251:33)
    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:125:19)
    at AwsInvokeLocal.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
    at process.topLevelDomainCallback (domain.js:101:23)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '//data/GeoLite2-City.mmdb' }
```

**Comment by janthonyeconomist** [comment]
I also attempted to use the geoip2 <https://github.com/davidtsai/node-geoip2> module, but it failed to load the compiled C module `var mmdb = require('./lib/node_mmdb.node');`.  It said I might be missing a loader.

**Comment by HyperBrain** [comment]
Hi @janthonyeconomist . The reason why your deployed code does not find the mmdb file is, because it is most likely not included in your deployed package.
You have to use the [copy webpack plugin](https://github.com/webpack-contrib/copy-webpack-plugin) and configure it in your `webpack.config.js` to copy the data folder or the mmdb file to your compiled output.

Additionally, you should update your tools:
```
Serverless-Webpack Version you're using: ^3.0.0
Webpack version you're using: ^3.6.0
```
Update `serverless-webpack` to 5.1.1 to use the latest features and bugfixes. Optionally I'd recommend to upgrade webpack to 4.x.x too.

**Comment by janthonyeconomist** [comment]
Thanks much!  Worked like a charm.
