### ISSUE TITLE
Can't get serverless webpack to deploy

### ISSUE THREAD

**Issue by adeshrd** [serverless-heaven/serverless-webpack#490]
# This is a request for help

## Description

I am trying to get my existing webpack configuration to work with serverless.

I am getting an error when I do `serverless deploy`
`TypeError: Cannot read property 'errors' of undefined`

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.2.0
* ***Webpack version you're using***: 1.12.6
* ***Serverless Framework Version you're using***: latest
* ***Operating System***: Linux
* ***Stack Trace (if available)***: 
```
TypeError: Cannot read property 'errors' of undefined
    at _.forEach.compileStats (/opt/here/lidar-tile-imagery/node_modules/serverless-webpack/lib/compile.js:33:40)
    at arrayEach (/opt/here/lidar-tile-imagery/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/opt/here/lidar-tile-imagery/node_modules/lodash/lodash.js:9344:14)
    at BbPromise.fromCallback.then.stats (/opt/here/lidar-tile-imagery/node_modules/serverless-webpack/lib/compile.js:30:11)
    at /opt/here/lidar-tile-imagery/node_modules/webpack/lib/MultiCompiler.js:105:3
    at /opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at /opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:361:13
    at /opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:246:17)
    at /opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:358:17
    at Compiler.<anonymous> (/opt/here/lidar-tile-imagery/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/opt/here/lidar-tile-imagery/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/opt/here/lidar-tile-imagery/node_modules/webpack/lib/Compiler.js:187:11)
    at /opt/here/lidar-tile-imagery/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/opt/here/lidar-tile-imagery/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/opt/here/lidar-tile-imagery/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/opt/here/lidar-tile-imagery/node_modules/webpack/lib/Compiler.js:267:14)
    at /opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/opt/here/lidar-tile-imagery/node_modules/webpack/node_modules/async/lib/async.js:209:22)
    at Compiler.emitFiles (/opt/here/lidar-tile-imagery/node_modules/webpack/lib/Compiler.js:235:20)
    at /opt/here/lidar-tile-imagery/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:407:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:425:17)
    at ServerlessWebpack.BbPromise.bind.then.then (/opt/here/lidar-tile-imagery/node_modules/serverless-webpack/index.js:101:51)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by christhekeele** [comment]
I just hit upon this too. @adeshrd I assume you closed this because it was a configuration error your side, but do you mind posting how you resolved it, since this now comes up on search results for this error?

**Comment by christhekeele** [comment]
For posterity, my issues were caused by #439.

**Comment by adeshrd** [comment]
Hi @christhekeele ,

The problem happened when I was trying to compile my vue client bundle along with my lambda.

I got tired of resolving unrelated errors and instead moved the compilation of client bundle (vue components) outside into a separate webpack file named webpack.frontend..configjs

Now, I run two commands to deploy my project:
webpack --config webpack.front.config.js
serverless deploy
