### ISSUE TITLE
Not working with "fork-ts-checker-webpack-plugin"

### ISSUE THREAD

**Issue by Can-Sahin** [serverless-heaven/serverless-webpack#508]
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* **What went wrong?**

Default installation and configuration with [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) is **NOT** working. It throws an error  `Cannot read property 'options' of undefined`. Normally it looks like that lib's problem but the comments in [related issue](https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/267) suggest that there might be some inconsistencies.

* **What stacktrace or error message from your provider did you see?**

```typescript
TypeError: Cannot read property 'options' of undefined
    at ForkTsCheckerWebpackPlugin.computeContextPath (/Users/xx/Git/xx/node_modules/fork-ts-checker-webpack-plugin/src/index.ts:344:36)
    at ForkTsCheckerWebpackPlugin.apply (/Users/xx/Git/xx/node_modules/fork-ts-checker-webpack-plugin/src/index.ts:278:30)
    at webpack (/Users/xx/Git/xx/node_modules/webpack/lib/webpack.js:47:13)
    at options.map.options (/Users/xx/Git/xx/node_modules/webpack/lib/webpack.js:35:55)
    at Array.map (<anonymous>)
    at webpack (/Users/xx/Git/xx/node_modules/webpack/lib/webpack.js:35:40)
    at ServerlessWebpack.compile (/Users/xx/Git/xx/node_modules/serverless-webpack/lib/compile.js:12:22)
```

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.0
* ***Webpack version you're using***: 4.30.0
* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by esetnik** [comment]
I have the same issue when using `fork-ts-checker-webpack-plugin` in conjunction with:

```
package:
  individually: true
```

**Comment by DASPRiD** [comment]
I took care of the issue, fixed in fork-s 1.3.6 via https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/299 (details over there).

**Comment by Can-Sahin** [comment]
Yes it works now thanks!. I cannot be sure if `serverless-webpack` has something to do here. If not, you can close the issue :)

**Comment by DASPRiD** [comment]
I'm not a collaborator here, but you as the reporter can close it ;)
