### ISSUE TITLE
Deployed lambda fails on "require"

### ISSUE THREAD

**Issue by nosuchip** [serverless-heaven/serverless-webpack#543]
# This is a Bug Report

## Description

Webpack package everything correct (I suppose it do because I see all dependencies directly used by my code) but when uploaded to AWS Lambda it looks like it running in a strange Node installation because failed on first `require` statement that includes Node's package (say - `crypto`).

Logs from Cloudwatch:
```
2019-10-21T17:47:27.370Z undefined ERROR Uncaught Exception
{
    "errorType": "TypeError",
    "errorMessage": "require is not a function",
    "stack": [
        "TypeError: require is not a function",
        "    at Object.webpackEmptyContext.keys (/var/task/api.js:22939:14)",
        "    at __webpack_require__ (/var/task/api.js:20:30)",
        "    at Object.<anonymous> (/var/task/api.js:22928:20)",
        "    at __webpack_require__ (/var/task/api.js:20:30)",
        "    at Object.<anonymous> (/var/task/api.js:9840:18)",
        "    at __webpack_require__ (/var/task/api.js:20:30)",
        "    at Object.<anonymous> (/var/task/api.js:9652:20)",
        "    at __webpack_require__ (/var/task/api.js:20:30)",
        "    at Object.exports.parse (/var/task/api.js:9371:17)",
        "    at __webpack_require__ (/var/task/api.js:20:30)"
    ]
```

## Additional Data
- "serverless-offline": "^5.12.0"
- "serverless-webpack": "^5.3.1"
- "webpack": "^4.41.2"
- "webpack-node-externals": "^1.7.2"
- Node 10

**Comment by sverraest** [comment]
Getting the exact same issues.
Using nodejs10.x on AWS Lambda using Serverless with serverless-webpack plugin,

**Comment by sverraest** [comment]
For anyone coming after this, inspected the code a bit more on Lambda and it seems it failed on 

`var crypto = require('crypto')`

Adding the following to my webpack.config.js worked

```
const webpack = require('webpack')
....
plugins: [
    new webpack.DefinePlugin({ 'global.GENTLY': false }),
  ]
```
