### ISSUE TITLE
When "npm" is spawned, there is no process.env.PATH to find it

### ISSUE THREAD

**Issue by SimoneGianniHNP** [serverless-heaven/serverless-webpack#565]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Russing "sls webpack" causes errror "spawn npm ENOENT" on linux.

* What did you expect should have happened?

No error.

* What was the config you used?

I have the following plugins:

```
plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-migrate-plugin
  - serverless-finch
  - serverless-offline
```

and I have a custom environment with names of dynamo db tables, like
```
provider:
  environment:
    TABLE_ABC=whatever_name
```

* What stacktrace or error message from your provider did you see?

```
  Error: spawn npm ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
      at onErrorNT (internal/child_process.js:456:16)
      at processTicksAndRejections (internal/process/task_queues.js:74:11)
```

## Additional Data

I think that some plugin overrides process.env, removing PATH, so child_process.spawn cannot find npm.

More specifically:
1. I have npm installed in a folder on my system
2. the env variable PATH contains also that folder, so I can type "npm" and it is found
3. child_process.spawn uses process.env by default, and uses process.env.PATH (directly or not) to find the command to execute
4. some plugin, or serverless itself, overrides process.env with values from provider.environment
5. when webpack tries to execute npm, child_process does not find process.env.PATH
6. child_process fails to run npm

I've verified the above adding logs here and there, and can confirm that re-adding PATH (for example in serverless-webpack utils.js setting process.env.PATH=".....") works.

However, the provider.environment is meant to be used for deployed code, not for running local tools, so this should be avoided. Either serverless-webpack uses the local env variables (at least PATH), or the other plugin (or whoever it is) does not pollute process.env.

* ***Serverless-Webpack Version you're using***:
5.3.1

* ***Webpack version you're using***:
4.42.0

* ***Serverless Framework Version you're using***:
1.67.1

* ***Operating System***:

Linux Ubuntu

* ***Stack Trace (if available)***:
```
  Error: spawn npm ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
      at onErrorNT (internal/child_process.js:456:16)
      at processTicksAndRejections (internal/process/task_queues.js:74:11)
```

**Comment by SimoneGianniHNP** [comment]
As a workaround it's possible to add:

```
provider:
  environment:
    PATH: ${env:PATH}
```

Your local path will end up also in the env of the deployed lambdas, and that may create problems, but at least webpack will be able to find npm locally while building.
