### ISSUE TITLE
WebpackOptionsValidationError: Invalid configuration object. configuration.entry should be an non-empty object

### ISSUE THREAD

**Issue by ggmartins** [serverless-heaven/serverless-webpack#592]
For bug reports:
* What went wrong?

webpack throwing an error running ```sls deploy``` or ```sls offline```

```
  Webpack Options Validation Error -----------------------
 
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
   - configuration.entry should be an non-empty object.

(full stack trace below)
```

* What did you expect should have happened?

no errors

* What was the config you used?
serverless.yml
```
service:
  name: serverless-iotlab

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-s3-local

...
```

package.json
```
{
  "name": "iotpro",
  "version": "0.0.1",
  "description": "IoT Device Managing and Profiling",
  "main": "handler.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Guilherme Martins",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.19.2",
    "http-aws-es": "^6.0.0",
    "jsonwebtoken": "^8.5.1",
    "middy": "^0.36.0",
    "source-map-support": "^0.5.19",
    "uuid": "^8.1.0"
  },
  "devDependencies": {
    "@types/jest": "^26.0.0",
    "@types/node": "^14.0.13",
    "aws-sdk": "^2.696.0",
    "aws-xray-sdk": "^3.1.0",
    "bcryptjs": "^2.4.3",
    "elasticsearch": "^16.7.1",
    "serverless": "^1.72.0",
    "serverless-aws-documentation": "^1.1.0",
    "serverless-dynamodb-local": "^0.2.39",
    "serverless-iam-roles-per-function": "^2.0.2",
    "serverless-offline": "^6.4.0",
    "serverless-reqvalidator-plugin": "^1.0.3",
    "serverless-s3-local": "^0.6.2",
    "serverless-webpack": "^5.3.2",
    "ts-loader": "^7.0.5",
    "typescript": "^3.9.5",
    "webpack": "^4.43.0"
  }
}
```
webpack.config.js (auto-generated)
```
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: 'source-map',
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: 'ts-loader' },
    ],
  },
};
```

* What stacktrace or error message from your provider did you see?
```
sls deploy
Serverless: Bundling with Webpack...
 
  Webpack Options Validation Error -----------------------
 
  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
   - configuration.entry should be an non-empty object.
     -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
      at webpack (/Users/gmartins/course/clouddev/iotpro/node_modules/webpack/lib/webpack.js:31:9)
      at ServerlessWebpack.compile (/Users/gmartins/course/clouddev/iotpro/node_modules/serverless-webpack/lib/compile.js:12:22)
      at ServerlessWebpack.tryCatcher (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/gmartins/course/clouddev/iotpro/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* #12345

## Additional Data

* ***Serverless-Webpack Version you're using***:
    "serverless-webpack": "^5.3.2",
* ***Webpack version you're using***:
    "webpack": "^4.43.0"
* ***Serverless Framework Version you're using***:
Framework Core: 1.72.0
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.30.14
* ***Operating System***:
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.1.0
     Framework Version:         1.72.0
     Plugin Version:            3.6.13
     SDK Version:               2.3.1
     Components Version:        2.30.14
* ***Stack Trace (if available)***:
(see above)

**Comment by nguyenxndaidev** [comment]
To find the actual problem, I think you should post your full serverless.yml.

**Comment by ggmartins** [comment]
thanks, that's ok, I fixed this by generating a new configuration from template:
```
sls create --template aws-nodejs-typescript --path iotpro
```
