### ISSUE TITLE
v5.3.3 has "match" error when trying to deploy

### ISSUE THREAD

**Issue by miguel-a-calles-mba** [serverless-heaven/serverless-webpack#628]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

Error during `sls deploy`.

* What did you expect should have happened?

Webpack should have happened like normal. I do not see this issue in `v5.3.2`.

* What was the config you used?

```js
'use strict';

const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
    entry: slsw.lib.entries,
    target: 'node',
    externals: [nodeExternals()], // exclude external modules
    mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
};
```

* What stacktrace or error message from your provider did you see?

```
  TypeError: Cannot read property 'match' of undefined
```

Similar or dependent issue(s):
* none

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.3.3
* ***Webpack version you're using***: 4.44.1
* ***Serverless Framework Version you're using***:  1.67.0
* ***Operating System***: darwin
* ***Stack Trace (if available)***:

```sh
  Type Error ---------------------------------------------
 
  TypeError: Cannot read property 'match' of undefined
      at /Users/mcalles/Code/serverless-webpack/lib/validate.js:101:21
      at arrayEach (/Users/mcalles/Code/serverless-webpack/node_modules/lodash/lodash.js:516:11)
      at Function.forEach (/Users/mcalles/Code/serverless-webpack/node_modules/lodash/lodash.js:9368:14)
      at ServerlessWebpack.validate (/Users/mcalles/Code/serverless-webpack/lib/validate.js:98:9)
      at ServerlessWebpack.tryCatcher (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/promise.js:517:31)
      at Promise._settlePromise (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/promise.js:574:18)
      at Promise._settlePromiseCtx (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/promise.js:611:10)
      at _drainQueueStep (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/async.js:142:12)
      at _drainQueue (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/async.js:131:9)
      at Async._drainQueues (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/async.js:147:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/mcalles/Code/serverless-webpack/node_modules/bluebird/js/release/async.js:17:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by j0k3r** [comment]
What's your `serverless.yml`? It looks weird to me that the `runtime` property can not be defined.

**Comment by miguel-a-calles-mba** [comment]
I didn't have `runtime` defined in the `provider` section. It's not required if you're deploying Node.js in AWS. Reference https://github.com/serverless/serverless/blob/master/lib/plugins/aws/provider/awsProvider.js#L669

Here's a sample of my `serverless.yml` file.

```yaml
service: my-stack

provider:
  name: aws
  stage: ${env:STAGE, opt:stage, 'dev'}
  region: us-west-2

functions:
  my-func:
    handler: src/my-func.handler

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: webpack.config.js
    packager: npm
    includeModules: true
```
