### ISSUE TITLE
Source map not working on AWS lambda

### ISSUE THREAD

**Issue by bhrigushr** [serverless-heaven/serverless-webpack#630]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
   **Error log stack traces not using source map**

* What did you expect should have happened?
   **Should use source map to log readable stack traces**

* What was the config you used?

`webpack.config.js` :
```javascript
const path = require('path')
const slsw = require('serverless-webpack')
const nodeExternals = require('webpack-node-externals')

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  optimization: {
    // We no not want to minimize our code.
    minimize: !slsw.lib.webpack.isLocal,
    nodeEnv: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  devtool: 'source-map',
  externals: [nodeExternals()],
  resolve: {
    alias: {
      app: path.join(process.cwd(), 'app')
    }
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
    sourceMapFilename: '[file].map'
  }
}

```

* What stacktrace or error message from your provider did you see?
` Error in insert items TypeError: Cannot read property 'toString' of undefined
    at e.value.a.find.t (/var/task/app/routes/import-data/item.js:1:13252)
    at Array.find (<anonymous>)
    at A.t.filter.e (/var/task/app/routes/import-data/item.js:1:13239)
    at Array.filter (<anonymous>)
    at A (/var/task/app/routes/import-data/item.js:1:13218)
    at E (/var/task/app/routes/import-data/item.js:1:12907)
    at N.a.map (/var/task/app/routes/import-data/item.js:1:10993)
    at Array.map (<anonymous>)
    at N (/var/task/app/routes/import-data/item.js:1:10980)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* #228 

## Additional Data

* ***Serverless-Webpack Version you're using***:
5.3.1
* ***Webpack version you're using***:
4.41.0
* ***Serverless Framework Version you're using***:
1.53.0
* ***Operating System***:
* ***Stack Trace (if available)***:
`Error in insert items TypeError: Cannot read property 'toString' of undefined
    at e.value.a.find.t (/var/task/app/routes/import-data/item.js:1:13252)
    at Array.find (<anonymous>)
    at A.t.filter.e (/var/task/app/routes/import-data/item.js:1:13239)
    at Array.filter (<anonymous>)
    at A (/var/task/app/routes/import-data/item.js:1:13218)
    at E (/var/task/app/routes/import-data/item.js:1:12907)
    at N.a.map (/var/task/app/routes/import-data/item.js:1:10993)
    at Array.map (<anonymous>)
    at N (/var/task/app/routes/import-data/item.js:1:10980)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

**Comment by smbkr** [comment]
Add the package `source-map-support` to your project's dependencies and then import it at the start of your entrypoint (ie. `index.js`):
```js
import 'source-map-support/register';
```

**Comment by j0k3r** [comment]
@bhrigushr have you tried what @smbkr recommended?
