### ISSUE TITLE
Error: GraphQL error: Cannot find module 'uuid'

### ISSUE THREAD

**Issue by orr-levinger** [serverless-heaven/serverless-webpack#676]
After installing the plugin with typescrypt configuration i got this error

webpack.config.js:

```
/* eslint-disable @typescript-eslint/no-var-requires */
const path = require('path');
const nodeExternals = require('webpack-node-externals');
const slsw = require('serverless-webpack');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');

const isLocal = slsw.lib.webpack.isLocal;

module.exports = {
  mode: isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  externals: [nodeExternals()],
  devtool: 'source-map',
  resolve: {
    extensions: [ '.js', '.jsx', '.json', '.ts', '.tsx' ]
  },
  output: {
    libraryTarget: 'commonjs2',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js'
  },
  target: 'node',
  module: {
    rules: [
      {
        // Include ts, tsx, js, and jsx files.
        test: /\.(ts|js)x?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'cache-loader',
            options: {
              cacheDirectory: path.resolve('.webpackCache')
            }
          },
          'babel-loader'
        ]
      }
    ]
  },
  plugins: [new ForkTsCheckerWebpackPlugin()]
};
```

tsconfig
```
{
  "compilerOptions": {
    "strictNullChecks": true,
    "allowJs": true,
    "outDir": ".build",
    "moduleResolution": "node",
    "lib": ["es2017"],
    "rootDir": "./",
    "module": "CommonJS",
    "preserveConstEnums": true,
    "target": "ES2017",
    "esModuleInterop": true,
    "inlineSources": true,
    "inlineSourceMap": true,
    "sourceRoot": "/",
    "resolveJsonModule": true,
    "sourceMap": true
  },
  "exclude": ["__tests__"]
}
```
.babelrc:
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "12"
        }
      }
    ],
    ["@babel/preset-typescript"]
  ]
}
```

Error: GraphQL error: Cannot find module 'uuid'
Require stack:
- /var/task/node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js
- /var/task/node_modules/aws-appsync-subscription-link/lib/index.js
- /var/task/node_modules/aws-appsync/lib/deltaSync.js
- /var/task/node_modules/aws-appsync/lib/cache/offline-cache.js
- /var/task/node_modules/aws-appsync/lib/cache/index.js
- /var/task/node_modules/aws-appsync/lib/client.js
- /var/task/node_modules/aws-appsync/lib/index.js
- /var/task/src/functions/matches/find-matches.js
- /opt/nodejs/node_modules/lumigo-auto-instrument/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js

    at new ApolloError (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/src/errors/ApolloError.ts:56:5)
    at /Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/src/core/QueryManager.ts:509:31
    at /Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/src/core/QueryManager.ts:1041:11
    at Array.forEach (<anonymous>)
    at /Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/src/core/QueryManager.ts:1040:10
    at Map.forEach (<anonymous>)
    at QueryManager.Object.<anonymous>.QueryManager.broadcastQueries (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/src/core/QueryManager.ts:1034:18)
    at Object.next (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/src/core/QueryManager.ts:1130:18)
    at notifySubscription (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/zen-observable/lib/Observable.js:235:7)
    at /Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/apollo-link-dedup/src/dedupLink.ts:50:48
    at Set.forEach (<anonymous>)
    at Object.next (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/apollo-link-dedup/src/dedupLink.ts:50:29)
    at notifySubscription (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/Users/orrlevinger/projects/BlindChat/blind-chat-backend/node_modules/zen-observable/lib/Observable.js:179:3)

**Comment by j0k3r** [comment]
What version are you using?
Can you try using the most recent version?
What nodejs version are you using?
