### ISSUE TITLE
sls local invoke fails with typescript decorators 

### ISSUE THREAD

**Issue by pankajanand18** [serverless-heaven/serverless-webpack#695]
# This is a Bug Report
sls local invoke fails with typescript decorators 
## Description
sls local invoke fails to load the decorator and it complains about experiment decorators are not enabled in tsconfig.json, but it is enabled. 
`sls offline start` and `sls deploy` works just fine without issues. 

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?
I tried to run the command like the following 
```shell
SLS_DEBUG=* AWS_PROFILE=YOURPOFILE sls invoke local --function hello
```
It generates the following error 
```shell
Error: make sure you have enabled the typescript compiler options which enable us to work with decorators (see doc)
    at createNewProperty (/Users/YourUserName/dev/serverless-webpack-decorator-problem/node_modules/@shiftcoders/dynamo-easy/src/decorator/impl/property/init-or-update-property.function.ts:48:11)
    at Object.initOrUpdateProperty (/Users/YourUserName/dev/serverless-webpack-decorator-problem/node_modules/@shiftcoders/dynamo-easy/src/decorator/impl/property/init-or-update-property.function.ts:31:16)
    at Property (/Users/YourUserName/dev/serverless-webpack-decorator-problem/node_modules/@shiftcoders/dynamo-easy/src/decorator/impl/property/property.decorator.ts:22:7)
    at eval (webpack:///./user.model.ts?:18:410)
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (webpack:///./user.model.ts?:18:367)
    at eval (webpack:///./user.model.ts?:53:27)
    at Object../user.model.ts (/Users/YourUserName/dev/serverless-webpack-decorator-problem/.webpack/service/handler.js:109:1)
    at __webpack_require__ (/Users/YourUserName/dev/serverless-webpack-decorator-problem/.webpack/service/handler.js:20:30)
    at eval (webpack:///./handler.ts?:8:13)
    at Object../handler.ts (/Users/YourUserName/dev/serverless-webpack-decorator-problem/.webpack/service/handler.js:97:1)
    at __webpack_require__ (/Users/YourUserName/dev/serverless-webpack-decorator-problem/.webpack/service/handler.js:20:30)
    at /Users/YourUserName/dev/serverless-webpack-decorator-problem/.webpack/service/handler.js:84:18
    at Object.<anonymous> (/Users/YourUserName/dev/serverless-webpack-decorator-problem/.webpack/service/handler.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:733:33)
    at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:216:19)
    at Object.invoke:local:invoke [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:49:47)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:501:55)
    at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
    at Object.gotAccum (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)

  Error --------------------------------------------------

  Error: Exception encountered when loading /Users/YourUserName/dev/serverless-webpack-decorator-problem/.webpack/service/handler
      at AwsInvokeLocal.invokeLocalNodeJs (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:738:13)
      at AwsInvokeLocal.invokeLocal (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:216:19)
      at Object.invoke:local:invoke [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:49:47)
      at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:501:55)
      at tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Object.gotValue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:168:18)
      at Object.gotAccum (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/reduce.js:155:25)
      at Object.tryCatcher (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/promise.js:729:18)
      at _drainQueueStep (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues (/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              10.23.3
     Framework Version:         2.25.2
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.0
```
For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* #12345

## Additional Data
repo with a reproducible error 
https://github.com/pankajanand18/serverless-webpack-decorator-problem

* ***Serverless-Webpack Version you're using***:
* ***Webpack version you're using***:
* ***Serverless Framework Version you're using***:
* ***Operating System***:
* ***Stack Trace (if available)***:

**Comment by pankajanand18** [comment]
this problem was solved with this change:
https://github.com/pankajanand18/serverless-webpack-decorator-problem/pull/3
