### ISSUE TITLE
Custom Runtime for multiple functions cannot deploy the functions

### ISSUE THREAD

**Issue by dannykaplunski** [serverless-heaven/serverless-webpack#763]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 
when tried serverless deploy got an error about not finding the zip of the function in .webpack. when looking in my .webpack folder i found a zip with the name of the service name instead of the function.
* What did you expect should have happened?
that the function would deploy to the aws lambda.
* What stacktrace or error message from your provider did you see?
`  Error: ENOENT: no such file or directory, copyfile '/Users/danny/Work/y2/.webpack/address-master.zip' -> '.serverless/address-master.zip'
      at copyFileSync (fs.js:1912:3)
      at Object.copyFileSync (/snapshot/serverless/lib/utils/standalone-patch.js:55:5)
      at ServerlessWebpack.copyArtifactByName (/Users/danny/Work/y2/node_modules/serverless-webpack/lib/packageModules.js:86:6)
      at /Users/danny/Work/y2/node_modules/serverless-webpack/lib/packageModules.js:133:66
      at arrayEach (/Users/danny/Work/y2/node_modules/serverless-webpack/node_modules/lodash/lodash.js:530:11)
      at Function.forEach (/Users/danny/Work/y2/node_modules/serverless-webpack/node_modules/lodash/lodash.js:9410:14)
      at ServerlessWebpack.copyExistingArtifacts (/Users/danny/Work/y2/node_modules/serverless-webpack/lib/packageModules.js:133:9)
      at ServerlessWebpack.tryCatcher (/Users/danny/Work/y2/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/danny/Work/y2/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/danny/Work/y2/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/danny/Work/y2/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/danny/Work/y2/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/danny/Work/y2/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/danny/Work/y2/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/danny/Work/y2/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)`

## Additional Data

* ***Serverless-Webpack Version you're using: 5.4.0***:
* ***Webpack version you're using: 4.44.2***:
* ***Serverless Framework Version you're using: 2.25.2***:

**Comment by j0k3r** [comment]
I think https://github.com/serverless-heaven/serverless-webpack/pull/794 released in 5.4.2 fixed that issue.
Can you update serverless-webpack and try again?

**Comment by levz0r** [comment]
I had the same issue is version 5.4.1 and can confirm that version 5.5.5 doesn't have this issue anymore.
