### ISSUE TITLE
Webpack compilation error

### ISSUE THREAD

**Issue by erikgreen-x** [serverless-heaven/serverless-webpack#802]
# This is a Bug Report

## Description
`sls package` fails with "Webpack compilation error".

Webpack Config:
```
const path = require('path');
const slsw = require('serverless-webpack');
// TSLint will include all files under src, not just referenced ones
var TSLintPlugin = require('tslint-webpack-plugin');

module.exports = {
  entry: slsw.lib.entries,
  devtool: 'source-map',
  resolve: {
    extensions: [
      '.js',
      '.jsx',
      '.json',
      '.ts',
      '.tsx'
    ],
    alias: {
      deepmerge$: path.resolve(__dirname, 'node_modules/deepmerge/dist/umd.js'),
    }
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  plugins: [
    new TSLintPlugin({
      files: ['./src/**.ts', './test/**.test.ts'],
      test: true,
      typeCheck: true,
      force: false,
      init: false
    })
  ],
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' },
    ],
  }
};
```

The error output is very, very long.  I've selected some of the specific error messages since many are the same.  I've redacted some path info:
```
Serverless: Bundling with Webpack...
ts-loader: Using typescript@2.9.2 and <path redacted>/tsconfig.json
Time: 16093ms
             Asset     Size  Chunks                    Chunk Names
    src/handler.js   7.3 MB       0  [emitted]  [big]  src/handler
src/handler.js.map  10.2 MB       0  [emitted]         src/handler
   [0] ./node_modules/aws-sdk/lib/core.js 2.49 kB {0} [built]
   [1] ./node_modules/aws-sdk/lib/node_loader.js 4.12 kB {0} [built]
   [6] ./node_modules/env-var/lib/accessors/string.js 67 bytes {0} [built]
  [24] external "util" 42 bytes {0} [not cacheable]
  [25] ./node_modules/env-var/lib/accessors/int.js 214 bytes {0} [built]
  [26] ./node_modules/env-var/lib/accessors/float.js 172 bytes {0} [built]
  [37] ./node_modules/env-var/lib/env-error.js 373 bytes {0} [built]
  [72] ./src/handler.ts 1.62 kB {0} [built]
  [73] ./node_modules/lodash/lodash.js 544 kB {0} [built]
  [74] (webpack)/buildin/module.js 517 bytes {0} [built]
  [75] ./node_modules/env-var/env-var.js 1.18 kB {0} [built]
  [76] ./node_modules/env-var/lib/variable.js 4.31 kB {0} [built]
  [88] ./src/aws.ts 1.19 kB {0} [built]
  [89] ./node_modules/aws-sdk/lib/aws.js 159 bytes {0} [built]
[1054] ./src/cronConfiguration.ts 3.61 kB {0} [built]
    + 1040 hidden modules

ERROR in <path redacted>/node_modules/@types/chai/index.d.ts
(124,9): error TS8020: JSDoc types can only be used inside documentation comments.

ERROR in <path redacted>/node_modules/@types/lodash/common/util.d.ts
(175,64): error TS2370: A rest parameter must be of an array type.

ERROR in <path redacted>/node_modules/@types/lodash/common/seq.d.ts
(65,35): error TS2370: A rest parameter must be of an array type.

ERROR in <path redacted>/node_modules/@types/lodash/common/object.d.ts
(1894,13): error TS2370: A rest parameter must be of an array type.

ERROR in <path redacted>/node_modules/@types/lodash/common/lang.d.ts
(33,35): error TS2370: A rest parameter must be of an array type.

ERROR in <path redacted>/node_modules/@types/lodash/common/function.d.ts
(35,35): error TS2370: A rest parameter must be of an array type.

ERROR in <path redacted>/node_modules/@types/lodash/common/array.d.ts
(176,44): error TS2304: Cannot find name 'unknown'.

ERROR in <path redacted>/node_modules/@types/lodash/common/common.d.ts
(12,20): error TS2370: A rest parameter must be of an array type.

Error ---------------------------------------------------
 
  Error: Webpack compilation error, see stats above
      at <path redacted>/node_modules/serverless-webpack/lib/compile.js:32:15
      at arrayEach (<path redacted>/node_modules/lodash/lodash.js:530:11)
      at Function.forEach (<path redacted>/node_modules/lodash/lodash.js:9410:14)
      at <path redacted>/node_modules/serverless-webpack/lib/compile.js:29:7
      at tryCatcher (<path redacted>/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (<path redacted>/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (<path redacted>/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (<path redacted>/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (<path redacted>/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (<path redacted>/node_modules/bluebird/js/release/promise.js:673:18)
      at <path redacted>/node_modules/bluebird/js/release/nodeback.js:42:21
      at<path redacted>/node_modules/webpack/lib/Compiler.js:265:13
      at Compiler.emitRecords (<path redacted>/node_modules/webpack/lib/Compiler.js:371:38)
      at <path redacted>/node_modules/webpack/lib/Compiler.js:258:10
      at <path redacted>/node_modules/webpack/lib/Compiler.js:364:12
      at next (<path redacted>/node_modules/tapable/lib/Tapable.js:218:11)
      at Compiler.<anonymous> (<path redacted>/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
      at Compiler.applyPluginsAsyncSeries1 (<path redacted>/node_modules/tapable/lib/Tapable.js:222:13)
      at Compiler.afterEmit (<path redacted>/node_modules/webpack/lib/Compiler.js:361:9)
      at <path redacted>/node_modules/webpack/lib/Compiler.js:350:15
      at <path redacted>/node_modules/async/dist/async.js:473:16
      at iteratorCallback (<path redacted>/node_modules/async/dist/async.js:1064:13)
      at <path redacted>/node_modules/async/dist/async.js:969:16
      at <path redacted>/node_modules/graceful-fs/graceful-fs.js:144:16
      at <path redacted>/node_modules/graceful-fs/graceful-fs.js:61:14
      at FSReqCallback.oncomplete (fs.js:156:23)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.18.3
     Framework Version:         2.35.0 (local)
     Plugin Version:            4.5.3
     SDK Version:               4.2.2
     Components Version:        3.9.0

```

## Additional Data
```
$ npm list serverless-webpack
sls-lambda-fan-out@1.0.0 <path redacted>
└── serverless-webpack@5.4.1
```

**Comment by vicary** [comment]
For TS8020 and TS2370, it's mostly related to older versions of TypeScript doesn't understand the types in current dependencies. You may either,
1. Upgrade typescript, ts-node and related transformer/bundlers, or
2. Downgrade your chai and lodash to a compatible version.

**Comment by m-bilal-dev9** [comment]
Hello, I'm also having same issue. can you please tell me who to get is resolved?

**Comment by j0k3r** [comment]
If people still have _that_ issue, check the latest comment from @vicary https://github.com/serverless-heaven/serverless-webpack/issues/802#issuecomment-947348094

Otherwise, open a different issue.
