### ISSUE TITLE
Webpack configuration not loading on compile

### ISSUE THREAD

**Issue by manuellp12** [serverless-heaven/serverless-webpack#907]
# This is a (Bug Report)

## Description

When deploying with serverless deploy I get the following error:

TypeError: Cannot read property 'stats' of undefined
      at ServerlessWebpack.compile (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/serverless-webpack/lib/compile.js:118:48)
      at ServerlessWebpack.tryCatcher (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)

Doing some debuging I found that compile.js is not getting the configuration from the serverless.yml, as I tried to print "this.webpackConfig" and it is empty.

module.exports = {
  compile() {
    this.serverless.cli.log('Bundling with Webpack...: '+this.webpackConfig);

    const configs = ensureArray(this.webpackConfig);
    const logStats = getStatsLogger(configs[0].stats, this.serverless.cli.consoleLog);

    if (!this.configuration) {
      return BbPromise.reject('Missing plugin configuration');
    }
    const concurrency = this.configuration.concurrency;

    return webpackConcurrentCompile(configs, logStats, concurrency).then(stats => {
      this.compileStats = { stats };
      return BbPromise.resolve();
    });
  }
};

For bug reports:
* What went wrong?
compile.js should be getting the config file from serverless.yml

* What did you expect should have happened?
That the compilation was successful

* What was the config you used?
Default config, using custom.webpack

* What stacktrace or error message from your provider did you see?

TypeError: Cannot read property 'stats' of undefined
      at ServerlessWebpack.compile (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/serverless-webpack/lib/compile.js:118:48)
      at ServerlessWebpack.tryCatcher (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/environment/co.com.ucloud.aws.lambda.sample/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
      at process.topLevelDomainCallback (domain.js:126:23)

Similar or dependent issue(s):
* #12345

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.5.1
* ***Webpack version you're using***: 
* ***Serverless Framework Version you're using***: 2.51
* ***Operating System***: Linux
* ***Stack Trace (if available)***:

**Comment by poliander** [comment]
Do you have a function defined in serverless.yml? I've had the same error which went away after defining a function. AFAIK sls supports deploying without creating a function but serverless-webpack does not.

**Comment by rmjwilbur** [comment]
Encountered this today. Definitely needs an informative warning/error message.

**Comment by vicary** [comment]
Would you mind sharing your `serverless.yml` or a minimum reproducing config for further analysis?

**Comment by rmjwilbur** [comment]
> Would you mind sharing your `serverless.yml` or a minimum reproducing config for further analysis?

I just forgot the functions: line., which in my case declares several functions:

functions: ${self:custom.common.functions}

**Comment by vicary** [comment]
This error is usually caused by incorrect configurations, I'll mark this issue as invalid for the moment.

If anyone is interested in improving the configuration validation message, please feel free to open a PR directly.
