### ISSUE TITLE
serverless-webpack causes `sls deploy function` to fail if function's runtime is not node

### ISSUE THREAD

**Issue by mkucharek** [serverless-heaven/serverless-webpack#935]
# This is a Bug Report

## Description

I'm using serverless-webpack for deploying typescript-based API. However, in the same project, there are a couple of legacy python functions. When I try to `sls deploy function` one of the python functions, serverless-webpack throws an error because it is not finding a matching handler (which is correct, there's no handler for a python function). The workaround for this issue is basically commenting out `serverless-webpack` plugin and retrying the single function deployment or deploying the whole service using `sls deploy`.

Ideally, in a case when a function to be deployed is not of `node` runtime, serverless-webpack should simply skip its execution instead of throwing an error and causing the function deployment to fail. 

Related stack trace:
```
 Serverless Error ----------------------------------------
 
  ServerlessError: No matching handler found for 'parse-psd' in '/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/api/actual'. Check your service definition.
      at getEntryExtension (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/serverless-webpack/lib/validate.js:55:15)
      at ServerlessWebpack.getEntryForFunction (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/serverless-webpack/lib/validate.js:90:19)
      at ServerlessWebpack.validate (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/serverless-webpack/lib/validate.js:116:41)
      at ServerlessWebpack.tryCatcher (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromiseCtx (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/promise.js:641:10)
      at _drainQueueStep (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/async.js:97:12)
      at _drainQueue (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/Users/mkucharek/Development/Workspaces/Slate/Slate-Admin-Panel-API/node_modules/bluebird/js/release/async.js:15:14)
      at processImmediate (internal/timers.js:464:21)

```

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.5.1
* ***Webpack version you're using***: 5.31.0
* ***Serverless Framework Version you're using***: 2.51.2

**Comment by j0k3r** [comment]
I think it might be a duplicate of https://github.com/serverless-heaven/serverless-webpack/issues/755
Can you confirm?

**Comment by mkucharek** [comment]
You're right, it's the exact same issue! Sorry, I must have missed that.. Let me close this one.
