### ISSUE TITLE
sls deploy function -f <func> fails if runtime is not defined at the function level

### ISSUE THREAD

**Issue by oduncan** [serverless-heaven/serverless-webpack#945]
# This is a Bug Report

## Description

For bug reports:
* What went wrong?

As a result of 5.5.2 and Do not run webpack on a single non-node function (#879):

running sls deploy function -f myFunctionName produces the following error: 

```
  TypeError: Cannot read property 'match' of undefined
      at isNodeRuntime (/home/ec2-user/dev/surgg/node_modules/serverless-webpack/lib/utils.js:112:18)
      at Object.before:deploy:function:packageFunction [as hook] (/home/ec2-user/dev/surgg/node_modules/serverless-webpack/index.js:111:13)
      at PluginManager.invoke (/home/ec2-user/dev/surgg/node_modules/serverless/lib/classes/PluginManager.js:579:20)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async PluginManager.run (/home/ec2-user/dev/surgg/node_modules/serverless/lib/classes/PluginManager.js:639:7)
      at async Serverless.run (/home/ec2-user/dev/surgg/node_modules/serverless/lib/Serverless.js:452:5)
      at async /usr/lib/node_modules/serverless/scripts/serverless.js:751:9

```

This only happens when runtime is not defined at the function level in the serverless config. Doesn't seem to default to the runtime defined at the provider level.

**Comment by j0k3r** [comment]
Will be fixed by https://github.com/serverless-heaven/serverless-webpack/pull/944
